# -*- coding: utf-8 -*-
"""gerador_alunos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EYF7ZYZUmUURe6ChifTdLBJEg1F2XDpu
"""

import pandas as pd
import numpy as np

def gerar_dados_alunos(num_linhas=1000, start_id=1003, seed=42):
    np.random.seed(seed)

    # 1. IDs sequenciais
    student_ids = np.arange(start_id, start_id + num_linhas)

    # 2. Idade (Predominantemente 15 a 18 anos)
    age = np.random.choice([15, 16, 17, 18], size=num_linhas, p=[0.2, 0.3, 0.3, 0.2])

    # 3. Gênero (0 ou 1)
    gender = np.random.choice([0, 1], size=num_linhas, p=[0.5, 0.5])

    # 4. Etnia (Categorias de 0 a 3)
    ethnicity = np.random.choice([0, 1, 2, 3], size=num_linhas, p=[0.6, 0.15, 0.15, 0.10])

    # 5. Escolaridade dos Pais (Categorias de 0 a 4)
    parental_education = np.random.choice([0, 1, 2, 3, 4], size=num_linhas, p=[0.05, 0.25, 0.4, 0.2, 0.1])

    # 6. Tempo de Estudo Semanal (Continuous float, ex: entre 1 e 25 horas)
    study_time_weekly = np.random.uniform(1.0, 25.0, size=num_linhas)

    # 7. Faltas (Inteiro entre 0 e 30, mais concentrado em poucas faltas)
    absences = np.random.negative_binomial(n=2, p=0.25, size=num_linhas)
    absences = np.clip(absences, 0, 30) # Garante limite de 30 faltas

    # 8. Variáveis Binárias (Tutoring, Extracurricular, Sports, Music, Volunteering)
    tutoring = np.random.choice([0, 1], size=num_linhas, p=[0.7, 0.3])
    parental_support = np.random.choice([0, 1, 2, 3, 4], size=num_linhas, p=[0.05, 0.15, 0.3, 0.3, 0.2])
    extracurricular = np.random.choice([0, 1], size=num_linhas, p=[0.6, 0.4])
    sports = np.random.choice([0, 1], size=num_linhas, p=[0.7, 0.3])
    music = np.random.choice([0, 1], size=num_linhas, p=[0.8, 0.2])
    volunteering = np.random.choice([0, 1], size=num_linhas, p=[0.85, 0.15])

    # 9. Cálculo do GPA correlacionado para dados realistas
    # GPA base é influenciado positivamente por estudo e suporte, negativamente por faltas
    gpa_base = 2.5 + (study_time_weekly * 0.05) - (absences * 0.06) + (parental_support * 0.1) + (tutoring * 0.15)
    # Adiciona um ruído normal para não ser puramente linear
    ruido = np.random.normal(0, 0.25, size=num_linhas)
    gpa = gpa_base + ruido
    gpa = np.clip(gpa, 0.0, 4.0) # Limites do GPA tradicional (0.0 a 4.0)

    # 10. GradeClass baseada no GPA (0.0=A, 1.0=B, 2.0=C, 3.0=D, 4.0=F)
    grade_class = np.zeros(num_linhas)
    grade_class[gpa >= 3.5] = 0.0
    grade_class[(gpa >= 3.0) & (gpa < 3.5)] = 1.0
    grade_class[(gpa >= 2.5) & (gpa < 3.0)] = 2.0
    grade_class[(gpa >= 2.0) & (gpa < 2.5)] = 3.0
    grade_class[gpa < 2.0] = 4.0

    # Montagem do DataFrame
    df = pd.DataFrame({
        'StudentID': student_ids,
        'Age': age,
        'Gender': gender,
        'Ethnicity': ethnicity,
        'ParentalEducation': parental_education,
        'StudyTimeWeekly': study_time_weekly,
        'Absences': absences,
        'Tutoring': tutoring,
        'ParentalSupport': parental_support,
        'Extracurricular': extracurricular,
        'Sports': sports,
        'Music': music,
        'Volunteering': volunteering,
        'GPA': gpa,
        'GradeClass': grade_class
    })

    return df

if __name__ == "__main__":
    # Quantidade de linhas que você deseja gerar
    quantidade = 200000

    print(f"Gerando {quantidade} linhas de alunos fictícios...")
    df_ficticio = gerar_dados_alunos(num_linhas=quantidade)

    # Salva o arquivo CSV
    nome_arquivo = "alunos_ficticios.csv"
    df_ficticio.to_csv(nome_arquivo, index=False)
    print(f"Arquivo '{nome_arquivo}' gerado com sucesso!")

    # Exibe as primeiras linhas geradas para conferência
    print("\nExemplo das primeiras linhas geradas:")
    print(df_ficticio.head(3).to_string())